# TCL File Generated by Component Editor 17.1
# Mon May 07 17:48:13 CEST 2018
# DO NOT MODIFY


# 
# keyboard_ci "keyboard_ci" v1.0
#  2018.05.07.17:48:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module keyboard_ci
# 
set_module_property DESCRIPTION ""
set_module_property NAME keyboard_ci
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME keyboard_ci
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ps2_ci
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ps2_ci.v VERILOG PATH ci_hw/ps2_ci.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 0
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave reset reset Input 1


# 
# connection point keycode
# 
add_interface keycode conduit end
set_interface_property keycode associatedClock ""
set_interface_property keycode associatedReset ""
set_interface_property keycode ENABLED true
set_interface_property keycode EXPORT_OF ""
set_interface_property keycode PORT_NAME_MAP ""
set_interface_property keycode CMSIS_SVD_VARIABLES ""
set_interface_property keycode SVD_ADDRESS_GROUP ""

add_interface_port keycode keycode external Input 8


# 
# connection point ps2_read
# 
add_interface ps2_read conduit end
set_interface_property ps2_read associatedClock ""
set_interface_property ps2_read associatedReset ""
set_interface_property ps2_read ENABLED true
set_interface_property ps2_read EXPORT_OF ""
set_interface_property ps2_read PORT_NAME_MAP ""
set_interface_property ps2_read CMSIS_SVD_VARIABLES ""
set_interface_property ps2_read SVD_ADDRESS_GROUP ""

add_interface_port ps2_read ps2_read external Output 1

