# TCL File Generated by Component Editor 17.1
# Mon Apr 30 15:01:13 CEST 2018
# DO NOT MODIFY


# 
# synth_ci "synth_ci" v1.0
#  2018.04.30.15:01:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module synth_ci
# 
set_module_property DESCRIPTION ""
set_module_property NAME synth_ci
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME synth_ci
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL synth_ci
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file synth_ci.v VERILOG PATH synth_ci/synth_ci.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 1
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave opcode n Input 2
add_interface_port nios_custom_instruction_slave data dataa Input 32
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave reset reset Input 1


# 
# connection point sounds_ctrl
# 
add_interface sounds_ctrl conduit end
set_interface_property sounds_ctrl associatedClock ""
set_interface_property sounds_ctrl associatedReset ""
set_interface_property sounds_ctrl ENABLED true
set_interface_property sounds_ctrl EXPORT_OF ""
set_interface_property sounds_ctrl PORT_NAME_MAP ""
set_interface_property sounds_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property sounds_ctrl SVD_ADDRESS_GROUP ""

add_interface_port sounds_ctrl sounds_ctrl sound_ctrl_bus Output 88


# 
# connection point effects_ctrl
# 
add_interface effects_ctrl conduit end
set_interface_property effects_ctrl associatedClock ""
set_interface_property effects_ctrl associatedReset ""
set_interface_property effects_ctrl ENABLED true
set_interface_property effects_ctrl EXPORT_OF ""
set_interface_property effects_ctrl PORT_NAME_MAP ""
set_interface_property effects_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property effects_ctrl SVD_ADDRESS_GROUP ""

add_interface_port effects_ctrl effects_ctrl effects_ctrl_bus Output 18

